### ISSUE TITLE
Problem locating usa_coastal_counties.csv

### ISSUE THREAD

**Issue by vmeursault** [calebrob6/migration-slr#1]
Thank you very much for providing the code in such a easy to follow manner. I am currently working through the notebooks and ran into an issue running notebook "06.2 Find Hurricane Affected Counties by Migration." The first cell of the Find Affected Counties section references  usa_coastal_counties.csv:

`f = open("data/processed/usa_coastal_counties.csv","r")
coastal_county_set = set(map(lambda x: "%05d" % (int(x.split("|")[0])), f.read().strip().split("\n")))
f.close()`

I double checked all the previous notebooks and wasn't able to find code that creates the file. The file also does not appear to in the downloaded data. 

This file is necessary to create hurricane_affected_counties.csv on which much of the analysis depends. Could you please provide the code needed to create usa_coastal_counties.csv or the file itself? Alternatively, if you could provide hurricane_affected_counties.csv, that would suit my purposes as well. 

Thank you again for your work on making this project easy to follow. I would appreciate any direction you could provide.

**Comment by calebrob6** [comment]
You're right, sorry about that! Just uploaded the file directly to the repo.

Best,
Caleb

**Comment by vmeursault** [comment]
Thank you very much!
